### ISSUE TITLE
Add headers security checks Github

### ISSUE THREAD

**Issue by tbille** [canonical-webteam/github-to-influx#4]

**Comment by squidsoup** [comment]
@lilyvidenova can you provide us with a contact for usabilla to make this feature request please? Currently they don't support specifying a secret for webhooks, as Github does.

**Comment by tbille** [comment]
Fixed in #7 
@squidsoup I am closing this issue since I didn't specified that this was related to github.

Another issue to track usabilla work. I am disabling usabilla in the meantime.
